FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/auth-api ./cmd/auth-api

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/auth-api /app/
COPY ./pkg /app/pkg

EXPOSE ${GRPC_PORT}
EXPOSE ${GATEWAY_PORT}

CMD ["/app/auth-api"]